- .github/workflows/build-containers.yml
This pushes the current README.md to docker hub when we tag a release
> Add step to the build action to push README.md

- .github/workflows/build-containers.yml
Fix path to README files when pushing to Dockerhub
fixes #48
> Fix path to README.md for docker hub publish

- docker-compose.yml
Will need a to be paired with PR to flowforge-driver-docker (to add the extra env var) and for the docs in flowforge
To enable, update all the `example.com` entries and uncomment the all the commented out sections
> First pass adding LetsEncrypt support

- etc/flowforge.yml
Change default hostname configuration for fileStore with `file-server` to work out of the box
Another solution is to change something in multiple docker-compose.yml files like the service name
Without that this error occurs in writing a file
`[error] failed to append to file: Error: Unknown Error`
> Fix fileStore hostname

- etc/flowforge-storage.yml
Change context.options.user to context.options.username
Otherwise the connection fails with
```ERROR: Failed to start: SequelizeConnectionError: no PostgreSQL user name specified in startup packet```
> Fix default context configuration

- setup-context-db.sh
Add double quotes
Avoid error
```
ERROR:  syntax error at or near "-"
```
> Fix identifiers with double quotes needed for the db name

- docker-compose.yml
- nginx/my-proxy.conf
fixes #92
Default nginx max client body size is 1m, Node-RED defaults to 5m 
#92
> Add config to set max body size

- docker-compose.yml
Make sure the acme-companion restarts if it fails so new certs are created.
> ensure acme-companion restarts on failure

- docker-compose.yml
- etc/flowforge.yml
- npm/README.md
- npm/conf/config.yaml
- npm/online/conf/config.yaml
- npm/online/populate.sh
- npm/online/temp/package.json
part of FlowFuse/flowfuse#3461
Adds support to build an offline npm registry for running on air gapped networks
https://github.com/FlowFuse/flowfuse/issues/3461
> NPM Registry cache for offline installs.

- npm/online/.gitignore
- npm/online/conf/config.yaml
- npm/online/populate.bat
- npm/online/populate.sh
Make the offline npm cache populate script work on windows
> Support npm offline for windows

- node-red-container/Dockerfile
When using the `privateCA` option the cert file is mounted on `/usr/local/ssl-certs/chain.pem` but the `ssl-certs` dir does not exist in the container. This is not a problem on k8s as the directory will be created, but this fails on docker.
> Ensure ssl-certs dir exists

- docker-compose.yml
The `latest` tag tracks git head which may be more likely to be broken
> Lock nginx-proxy to a fixed tag

- docker-compose-quick-start.yml
This pull request introduces a docker compose file which allows to spin up the FlowFuse platform without the need to clone the whole repository. This file is used in the Quick Start guide.
Should be merged together with https://github.com/FlowFuse/flowfuse/pull/4639
https://github.com/FlowFuse/flowfuse/issues/4631
> Introduce quick-start compose file

- docker-compose.yml
This pull request removes an interpolation while creating a content of TLS certificate and key files.
> fix: Remove interpolation when creating TLS certificates

- docker-compose.yml
Revert the change of service name so exising Node-RED instances can reconnect to the New EQMX broker after an upgrade.
> Ensure the broker service name doesn't change

- UPGRADE.md
This pull request adds minor adjustments and clarifications to the docker compose upgrade instruction.
> docs: Adjust UPGRADE instruction

- docker-compose.yml
Ensure the default 1mb packet size is overrident
Tuning FFC
> Bump max MQTT packet to 128mb

- docker-compose.yml
Fix the indentation for the commented out block so it's consistent.
The hash and a single space after should be removed to enable this section.
> Fix indentation on team broker TLS section.

- .github/workflows/build-containers.yml
This pull request adds the `release-compose-files` job to the `Build and push containers` workflow. The job is responsible for adding `docker-compose.yml` and `docker-compose-quick-start.yml` files as assets to the coresponding release.
> ci: Add Docker Compose files as assets to a release

- .github/workflows/test-docker-compose.yaml
This pull requests ensures that `Test Docker Compose` workflow will not be launched agains branches matching pattern `release-*`.
This will stop tests execution during the release process.
Closes https://github.com/FlowFuse/docker-compose/issues/171
> ci: Do not run test against `release-*` branches

- flowforge-docker/Dockerfile
- flowforge-docker/install-device-cache.sh
Adds @node-red/editor-client cache files for Device Editor access
FlowFuse/flowfuse#3414
> Add node-red editor cache files

- CHANGELOG.md
- docker-compose.yml
- file-server/package.json
- flowforge-docker/package.json
- node-red-container/package.json
- **Update CHANGELOG for 2.12.0**
- **Update version to 2.12.0**
> Release 2.12.0

- .github/workflows/test-docker-compose.yaml
This pull request assures, that `Test Docker Compose` pipeline:
* will not run against `release-*` branch
* will wait for completion of `Build and push containers` workflow  before proceeding
> ci: Wait for containers to build before testing docker compose

- .github/workflows/build-containers.yml
This pull request removes `Resync Maintenance` step from the `Build and push containers` workflow.
Closes https://github.com/FlowFuse/helm/issues/486
> ci: Remove `Resync Maintenance` step from the pipeline

- docker-compose-quick-start.yml
- docker-compose.yml
This pull request ensures, that configuration option responsible for using persistent storage by Node-RED instances is enabled by default on both docker compose yaml files.
> feat: Enable storage for Node-RED intances

- .github/workflows/build-containers.yml
- .github/workflows/test-docker-compose.yaml
This pull request pins external GitHub Actions to commit hashes instead of tags in all workflows.
https://github.com/FlowFuse/CloudProject/issues/663
> chore: Pin external actions to commit hash

- docker-compose.yml
Adds `restart: always` policy to the broker service in the docker-compose.yml.
Ensures that the MQTT broker container automatically restarts after Docker daemon or host restarts, improving stability and uptime of the service in typical deployment environments.
> Add restart: always policy to broker service in docker-compose.yml
