FlowFuse/docker-compose

- etc/flowforge.yml
matches up with https://github.com/flowforge/flowforge/pull/311
> Add default host config value of 0.0.0.0

- README.md
- docker-compose-local-dev.yml
- flowforge-docker-local-dev/Dockerfile
- flowforge-docker-local-dev/package.json
Experimental mode where you can run the docker setup using a local source tree - with live rebuild/restart of the forge app when you edit.
> Add dev mode compose file

- CHANGELOG.md
- flowforge-docker/package.json
- node-red-container/package.json
- Update CHANGELOG for 0.4.0
- Update version to 0.4.0
> Release 0.4.0

- README.md
Documentation to update the VIRTUAL_HOST value to match the domain was missing
Fixes https://github.com/flowforge/flowforge/issues/482
> Fix virtual host

- CHANGELOG.md
- flowforge-docker/package.json
- node-red-container/package.json
- Update CHANGELOG for 0.5.0
- Update version to 0.5.0
> Release 0.5.0

- CHANGELOG.md
- flowforge-docker/package.json
- node-red-container/package.json
- Update CHANGELOG for 0.6.0
- Update version to 0.6.0
> Release 0.6.0

- broker/mosquitto.conf
- docker-compose.yml
- etc/flowforge.yml
Part of https://github.com/flowforge/flowforge/issues/464
> First pass of adding broker

- node-red-container/package.json
fixes #25
Adds dependency for @flowforge/nr-project-nodes
To be merged after @flowforge/nr-project-nodes are published to NPM
> add dep @flowforge/nr-project-nodes

- broker/mosquitto.conf
> Fix broker comms http auth path

- CHANGELOG.md
- flowforge-docker/package.json
- node-red-container/package.json
- Update CHANGELOG for 0.8.0
- Update version to 0.8.0
> Release 0.8.0

- broker/mosquitto.conf
> Fix http port for authentication API

- CHANGELOG.md
- flowforge-docker/package.json
- node-red-container/package.json
- Update CHANGELOG for 0.9.0
- Update version to 0.9.0
> Release 0.9.0

- .github/workflows/build-containers.yml
Same structure as https://github.com/flowforge/helm/pull/43 for the helm builds.
No need to build the node-red container as it is currently the same as the one built by the helm build
> First pass at GH Action to build docker-compose app container

- node-red-container/Dockerfile
Allows us to build @beta or @nightly containers
> Add build tag when installing nr-launcher

- flowforge-docker/Dockerfile
- node-red-container/Dockerfile
Also add support for npm registry auth token
> Set default python location for npm

- CHANGELOG.md
- flowforge-docker/package.json
- node-red-container/package.json
- Update CHANGELOG for 0.10.0
- Update version to 0.10.0
> Release 0.10.0

- .github/workflows/build-containers.yml
Ensure that the container gets tagged
> Set docker tags

- docker-compose.yml
Postrges have released v15 which breaks the setup-db.sh script
fixes #43
> Pin to Postgres 14

- node-red-container/package.json
They already dependencies of the launcher
part of https://github.com/flowforge/helm/issues/55
> Remove FlowForge nodes from /data/package.json

- CHANGELOG.md
- flowforge-docker/package.json
- node-red-container/package.json
- Update CHANGELOG for 1.0.0
- Update version to 1.0.0
> Release 1.0.0

- CHANGELOG.md
- flowforge-docker/package.json
- node-red-container/package.json
- Update CHANGELOG for 1.1.0
- Update version to 1.1.0
> Release 1.1.0

- build-containers.sh
- docker-compose.yml
- file-server/Dockerfile
- file-server/README.md
- file-server/package.json
> Add ability to build file-server locally

- docker-compose.yml
depending on how it's done in Dockerfile change flowforge-file-storage by flowforge-file-server
> Change working directory in volumes section

- node-red-container/Dockerfile
- node-red-container/healthcheck.js
Update NR `healthcheck.js` to not need to load `/data/settings.js`
Fixes #61
> Fix healthcheck

- node-red-container/healthcheck.js
Need to make http not https request
Sorry Steve
> Picked wrong bit of if block

- README.md
- docker-compose.yml
- etc/flowforge-storage.yml
- setup-context-db.sh
Also add upgrade instructions to README.md
> Add Context store to docker compose

- etc/flowforge-storage.yml
> Set quota defaults

- CHANGELOG.md
- flowforge-docker/package.json
- node-red-container/package.json
- Update CHANGELOG for 1.2.0
- Update version to 1.2.0
> Release 1.2.0

- docker-compose.yml
Ensure that scripts run in the correct order
Part of flowforge/flowforge#1496
> Ensure DB setup scripts run in the correct order

- CHANGELOG.md
- flowforge-docker/package.json
Update to include FlowForge 1.2.1
- [-] Suitable unit/system level tests have been added and they pass
- [-] Documentation has been updated
- [-] Upgrade instructions
- [-] Configuration details
- [-] Concepts
- [-] Backport needed? -> add the `backport` label
- [-] Includes a DB migration? -> add the `area:migration` label
> Bump versions for 1.2.1

- CHANGELOG.md
- flowforge-docker/package.json
- node-red-container/package.json
- Update CHANGELOG for 1.3.0
- Update version to 1.3.0
> Release 1.3.0

- CHANGELOG.md
- flowforge-docker/package.json
- node-red-container/package.json
- Update CHANGELOG for 1.4.0
- Update version to 1.4.0
> Release 1.4.0

- CHANGELOG.md
- file-server/package.json
- flowforge-docker/package.json
- node-red-container/package.json
- Update CHANGELOG for 1.7.0
- Update version to 1.7.0
> Release 1.7.0

- CHANGELOG.md
- file-server/package.json
- flowforge-docker/package.json
- node-red-container/package.json
Version number bump for maintenance release
> v1.7.1 point release

- CHANGELOG.md
- flowforge-docker/package.json
> Bump to 1.7.2

- CHANGELOG.md
- file-server/package.json
- flowforge-docker/package.json
- node-red-container/package.json
- Update CHANGELOG for 1.10.0
- Update version to 1.10.0
> Release 1.10.0

- CHANGELOG.md
- file-server/package.json
- flowforge-docker/package.json
- node-red-container/package.json
- Update CHANGELOG for 1.11.0
- Update version to 1.11.0
> Release 1.11.0

- .github/workflows/build-containers.yml
Make sure the maintenance branch gets resyn'd on a 4 weekly release
> Add step to end of release action to reset maintenance

- CHANGELOG.md
- flowforge-docker/package.json
> Bump to 1.11.3

- README.md
part of flowforge/flowforge#2830
Note Docker Compose version
Also change all (none container name) references from FlowForge to FlowFuse
flowforge/flowforge#2830
> Add note about docker-compose version

- CHANGELOG.md
- file-server/package.json
- flowforge-docker/package.json
- node-red-container/package.json
- Update CHANGELOG for 1.12.0
- Update version to 1.12.0
> Release 1.12.0

- .github/workflows/build-containers.yml
> ensure sync to maintenace works

- .github/workflows/project-automation.yml
Reusable workflow reference change.
> Reusable workflow reference change

- CHANGELOG.md
- flowforge-docker/package.json
> Bump to 1.12.1

- CHANGELOG.md
- flowforge-docker/package.json
> Bump to v1.12.2

- CHANGELOG.md
- file-server/package.json
- flowforge-docker/package.json
- node-red-container/package.json
- Update CHANGELOG for 1.13.0
- Update version to 1.13.0
> Release 1.13.0

- CHANGELOG.md
- flowforge-docker/package.json
> Bump for v1.13.1 release

- node-red-container/Dockerfile
Update to build using the newly migrated launcher package
> Update to @flowfuse/nr-launcher

- CHANGELOG.md
- file-server/package.json
- flowforge-docker/package.json
- node-red-container/package.json
- Update CHANGELOG for 1.14.0
- Update version to 1.14.0
> Release 1.14.0

- file-server/README.md
- file-server/package.json
- flowforge-docker-local-dev/package.json
- flowforge-docker/package.json
Do not merge until https://github.com/FlowFuse/driver-docker/pull/77 is complete and I verify the new packages are published.
> Update file server and driver-docker npm references

- CHANGELOG.md
- flowforge-docker/package.json
Update versions and Changelog for v1.14.1
> Bump versions for v1.14.1

- file-server/Dockerfile
- flowforge-docker/Dockerfile
- node-red-container/Dockerfile
part of https://github.com/FlowFuse/flowfuse/issues/2245
Bump base containers to NodeJS 18 to pick up CVE updates
> Update containers to NodeJS 18 base

- file-server/Dockerfile
- flowforge-docker-local-dev/package.json
- flowforge-docker/Dockerfile
- flowforge-docker/package.json
- node-red-container/Dockerfile
Updates the FlowFuse container to install `@flowfuse/flowfuse`.
Depends on https://github.com/FlowFuse/flowfuse/pull/3190 being merged and initial package published.
> Update to new flowfuse npm scope

- CHANGELOG.md
- file-server/package.json
- flowforge-docker/package.json
- node-red-container/package.json
- Update CHANGELOG for 1.15.0
- Update version to 1.15.0
> Release 1.15.0

- .github/workflows/build-containers.yml
part of FlowFuse/admin#212
Publish containers to both flowforge and flowfuse org name
FlowFuse/admin#212
> Push to both container names

- CHANGELOG.md
- file-server/package.json
- flowforge-docker/package.json
- node-red-container/package.json
- Update CHANGELOG for 2.0.0
- Update version to 2.0.0
> Release 2.0.0

- CHANGELOG.md
- flowforge-docker/package.json
- update Changelog
- update package.json for forge container
> Bump for v2.0.1 release

- CHANGELOG.md
- file-server/package.json
- flowforge-docker/package.json
- node-red-container/package.json
- Update CHANGELOG for 2.1.0
- Update version to 2.1.0
> Release 2.1.0

- .github/workflows/build-containers.yml
Fix last step in release GH Action
> Fix sync to maintenance branch

- docker-compose.yml
part of FlowFuse/admin#212
Not to be merged before #116 
FlowFuse/admin#212
> Rename containers 2

- README.md
- build-containers.sh
Update README.me and build script to use flowfuse scoped container images
> Rename containers in README and build script

- CHANGELOG.md
- file-server/package.json
- flowforge-docker/package.json
- node-red-container/package.json
- Update CHANGELOG for 2.2.0
- Update version to 2.2.0
> Release 2.2.0

- CHANGELOG.md
- flowforge-docker/package.json
> Bump for 2.2.2 release

- CHANGELOG.md
- file-server/package.json
- flowforge-docker/package.json
- node-red-container/package.json
- **Update CHANGELOG for 2.3.0**
- **Update version to 2.3.0**
> Release 2.3.0

- CHANGELOG.md
- file-server/package.json
- flowforge-docker/package.json
- node-red-container/package.json
- Update CHANGELOG for 2.4.0
- Update version to 2.4.0
> Release 2.4.0

- CHANGELOG.md
- file-server/package.json
- flowforge-docker/package.json
- node-red-container/package.json
- Update CHANGELOG for 2.5.0
- Update version to 2.5.0
> Release 2.5.0

- node-red-container/Dockerfile
pre-req for https://github.com/FlowFuse/nr-launcher/pull/250
Also sync up node-red-container/Dockerfile with Helm so the same default base container is build locally
> Add storage path to /data

- CHANGELOG.md
- file-server/package.json
- flowforge-docker/package.json
- node-red-container/package.json
- Update CHANGELOG for 2.6.0
- Update version to 2.6.0
> Release 2.6.0

- CHANGELOG.md
- flowforge-docker/package.json
> Bump to 2.6.1

- node-red-container/Dockerfile
part of fix for FlowFuse/flowfuse#4037
> rebrand working dir

- docker-compose.yml
part of https://github.com/FlowFuse/flowfuse/issues/4117
Adds mount point for persistent storage.
The dir needs to be mounted in the forge container so it can create the directories and remove them when the Instance deleted
https://github.com/FlowFuse/flowfuse/issues/4117
> Add mount for persistent-storage

- CHANGELOG.md
- file-server/package.json
- flowforge-docker/package.json
- node-red-container/package.json
- **Update CHANGELOG for 2.7.0**
- **Update version to 2.7.0**
> Release 2.7.0

- CHANGELOG.md
- file-server/package.json
- flowforge-docker/package.json
- node-red-container/package.json
- Update CHANGELOG for 2.8.0
- Update version to 2.8.0
> Release 2.8.0

- node-red-container/Dockerfile
Wait for NR 3.1.x container builds
> Bump Node-RED base container

- CHANGELOG.md
- file-server/package.json
- flowforge-docker/package.json
- node-red-container/package.json
- **Update CHANGELOG for 2.9.0**
- **Update version to 2.9.0**
> Release 2.9.0

- CHANGELOG.md
- file-server/package.json
- flowforge-docker/package.json
- node-red-container/package.json
- Update CHANGELOG for 2.10.0
- Update version to 2.10.0
> Release 2.10.0

- node-red-container/Dockerfile
> Update Node-RED version in Docker compose

- .github/workflows/test-docker-compose.yaml
- docker-compose.yml
This pull request introduces Github Actions workflow for performing basic testing of FlowFuse stacks deployed with our Docker Compose files.
Closes https://github.com/FlowFuse/docker-compose/issues/163
> ci: Introduce workflow for testing docker compose

- CHANGELOG.md
- docker-compose.yml
- file-server/package.json
- flowforge-docker/package.json
- node-red-container/package.json
- **Update CHANGELOG for 2.11.0**
- **Update version to 2.11.0**
> Release 2.11.0

- node-red-container/Dockerfile
Bump Node-RED Dockerfile to 3.1.15
> Update Node-RED Dockerfile to 3.1.15

- CHANGELOG.md
- file-server/package.json
- flowforge-docker/package.json
- node-red-container/package.json
- **Update CHANGELOG for 2.13.0**
- **Update version to 2.13.0**
> Release 2.13.0

- CHANGELOG.md
- docker-compose.yml
- file-server/package.json
- flowforge-docker/package.json
- node-red-container/package.json
> 2.13.1 Release

- CHANGELOG.md
- docker-compose.yml
- file-server/package.json
- flowforge-docker/package.json
- node-red-container/package.json
- Update CHANGELOG for 2.14.0
- Update version to 2.14.0
> Release 2.14.0

- CHANGELOG.md
- docker-compose.yml
- file-server/package.json
- flowforge-docker/package.json
- node-red-container/package.json
- **Update CHANGELOG for 2.14.1**
- **Update version to 2.14.1**
> Release 2.14.1

- CHANGELOG.md
- docker-compose.yml
- file-server/package.json
- flowforge-docker/package.json
- node-red-container/package.json
- **Update CHANGELOG for 2.15.0**
- **Update version to 2.15.0**
> Release 2.15.0

- flowforge-docker/install-device-cache.sh
Update Device agent proxy cache
> update device cache

- CHANGELOG.md
- docker-compose.yml
- file-server/package.json
- flowforge-docker/package.json
- node-red-container/package.json
- **Update CHANGELOG for 2.16.0**
- **Update version to 2.16.0**
> Release 2.16.0

- CHANGELOG.md
- docker-compose.yml
- file-server/package.json
- flowforge-docker/package.json
- node-red-container/package.json
- **Update CHANGELOG for 2.17.0**
- **Update version to 2.17.0**
> Release 2.17.0

- CHANGELOG.md
- docker-compose.yml
- file-server/package.json
- flowforge-docker/package.json
- node-red-container/package.json
- **Update CHANGELOG for 2.19.0**
- **Update version to 2.19.0**
> Release 2.19.0

- CHANGELOG.md
- docker-compose.yml
- file-server/package.json
- flowforge-docker/package.json
- node-red-container/package.json
- **Update CHANGELOG for 2.21.0**
- **Update version to 2.21.0**
> Release 2.21.0

- CHANGELOG.md
- docker-compose.yml
- file-server/package.json
- flowforge-docker/package.json
- node-red-container/package.json
- **Update CHANGELOG for 2.21.1**
- **Update version to 2.21.1**
> Release 2.21.1

- CHANGELOG.md
- docker-compose.yml
- file-server/package.json
- flowforge-docker/package.json
- node-red-container/package.json
- **Update CHANGELOG for 2.22.0**
- **Update version to 2.22.0**
> Release 2.22.0
